[package]
name = "compute-fields"
version = "0.1.0"
authors = ["vedhavyas <vedhavyas.singareddi@gmail.com>"]
edition = "2018"

[dependencies]
parity-scale-codec = "1.3.1"
parity-scale-codec-derive = "1.2.0"
